### ISSUE TITLE
Do initial move-around/clean up of documentation...

### ISSUE THREAD

**Issue by madscientist42** [madscientist42/runit#1]
The docs are split between the "packaging" directory and the docs one.  Need to fix that and a few other things. documentation-wise, so we can do packaging proper between the major distro packaging types and leave it easy for a Linux Plumber for one of the less common distributions to package according to their framework.

**Comment by ghost** [comment]
The use of the packaging directory itself seemed a bit confusing and odd when I first looked at this.  This may well be solved as part of the migration to cmake.  Yes, packaging, outside of producing a source tarball, is usually a distro function, not an upstream one.

**Comment by madscientist42** [comment]
Yeah, that was my take on this.  There should be some of this in a local docs directory that stays within the project, and some of this in a target docs directory.  I'll be getting started on morphing this shortly.  I'm going to be adding you to the project official here in a moment.

**Comment by MarkoShiva** [comment]
Guys if you need help I'm available. Maybe just an automation or testing of new runit in virtual machine or on barebones machine. Hopefully you will improve te runit. :) Do you guys work via forking repos and pull requests or directly on the repo. Anyway I haven't studied code of runit so I wouldn't be that helpful on changing the code directly but I can ask some guys form Devuan to package it once its finished.
Btw void linux have pretty nice implementation of runit.

**Comment by madscientist42** [comment]
We'll be tapping you shortly @in1t3r, I suspect we've a tiger by the tail and will need/appreciate the hel.

**Comment by madscientist42** [comment]
Issue completed.   Intial re-work of structure done, builds in CMake accordingly.  Closing.
