### ISSUE TITLE
svlogd is not built

### ISSUE THREAD

**Issue by dslm4515** [madscientist42/runit#12]
Looks like svlogd is not built. I checked the src/CMakeLists.txt and svlogd is not listed.

Is there a reason svlogd is not built? If so, what would be an alternative?

**Comment by madscientist42** [comment]
Just saw this.  Don't know why it's not getting built (it should)- will review and fix accordingly.  This is a, "Should Be There," thing.

**Comment by madscientist42** [comment]
It's building now and being relied upon by a vendor specific bespoke distribution.
