### ISSUE TITLE
bsd migrated to utmpx.h

### ISSUE THREAD

**Issue by ghost** [madscientist42/runit#4]
This effects utmpset.c and ut_tmp.h.  I did only the minimal changes needed to get this to compile and added a test for utmpx.h to cmake.  The utmpset.c utmpx.h support still probably needs to be re-written when building for modern bsd's...

**Comment by madscientist42** [comment]
First cut of this has been done.  Will revisit under the audit/code clean-up issue being put in today.  Closing.
