### ISSUE TITLE
Code Audit for Security/Robustness

### ISSUE THREAD

**Issue by madscientist42** [madscientist42/runit#6]
This will be an ongoing issue for a while.  We need to review and modify as needed, the code base to match current best practices for stability and security.  While I'm not one to say it's not robust (Void and others are using it...), we've found a few head-scratchers in the codebase that lead to a need/desire to verify what all is in the codebase.

**Comment by madscientist42** [comment]
Ongoing. Re-started with a fresh eye on what is and isn't an issue. Running static tests where possible with several tools. Current pass is using Cppcheck to do catches on gross failures. Already have several corrections made just due to purely dodgy stuff in the codebase on the first audit pass right now.

**Comment by MarkoShiva** [comment]
So what do you think about using open source process while handling the open source project.
I mean you sound here like a some representative from the proprietary company trying to say that the code they borrowed had problems but they will handle that.

**Comment by MarkoShiva** [comment]
The proper way to address open-source project especially when borrowing other people codebase is actually to first always make a notice its a fork. Other and more important is to open an issue for every bug found in the codebase. People who plan to use the project shouldn't believe your word that is why we have open-source way of doing things. 
So if you want anyone to take project seriously just make it transparent open issues for each bug or group of bugs and close issue once they are fixed. I'm sure project will get more people following then.

**Comment by madscientist42** [comment]
Considering that I was using it, you're a bit clueless.  Either step up and help, or wander off.

If I took a while to get back to a bug...it might be because I'm the only one dealing with things at the time.
